Feature/data hiramoto css 231013
twinbee-official/it_freelance pull request #8
Opened 2023-10-13 06:09 UTC by twinbee-s-hiramoto

## 変更の概要

SCSSおよびCSSの構築

## なぜこの変更をするのか

* CSSでデザインを反映するため。

## やったこと

特になし

## 変更内容

* モバイルレスポンシブ(375px)修正

## 影響範囲

特に無し

## どうやるのか

なし

## 課題

詳しくは[QA表](https://docs.google.com/spreadsheets/d/1IMr8pAzi3q2-ZiOvmXbirBou6yT3P_cRQraf-ueFU5I/edit#gid=2048494208)に記載。

## 備考
* 作業途中のため、デザイン崩れが激しいです。
* このPRではSCSSファイル、およびCSSファイルの変更のみレビュー依頼して下さい。

2023-10-14 05:43 UTC, twinbee-a-takahashi requested changes
書かれている修正はもちろんなのですが、
全体的にコード見直してください。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	@include mq('sp'){
まず、{の前には必ず半角を入れることを徹底してください。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	@include mq('sp'){
spは文字列じゃなくて大丈夫です。
```
@include(sp) { ... }
@include(tab) { ... }
```
で動きます。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			font-size: 18px;
font-size がrem指定ではなくなっている

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +				font-size: 64px;
上記同様です。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			font-size: 14px;
上記同様です。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		padding:64px 0px;
mの方がアルファベットでは先に来るので順番入れ替え。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			width: 311px;
mobileなのに絶対値を使っているのが気になる。
min()かmax()で修正してフレキシブルにしておいてください。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			width: 311px;
上記同様

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			font-size: 14px;
rem

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>      height: 45px;
この辺タブではなくてスペースでインデント取っているみたいなのでタブで統一しておいてください。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	@include mq('sp'){
レビュー時に空のもので提出しないこと。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +
不要な改行は残さない。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  		// width: 1072px;
ゴミコード残さない。

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			padding:20px 8px;
: の後ろにスペースがない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  		padding:36px 20px 12px 20px;
: の後ろにスペースがない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			font-size: 14px;
rem

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +
不要改行あり

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  	-moz-transform: rotate(-10deg);
ベンプレは不要なので削除

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		font-size: 32px;
rem

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		width: 143.5px;
minあるいはmaxで

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		padding:64px 0px;
: の後ろにスペースがない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	.faq_list {
変なスペース入ってる

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +				font-size: 14px;
rem

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +
不要な改行

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  .free_memberRegist_formBox {
入れ子になっていないのと、プロパティがインデントされていない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	font-size: 12px;
rem

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			width: 343px;
tablet＆mobileは絶対値を使わない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  		color: #fff;
変数を使っていない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			width: 343px;
絶対値使わない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			font-size: 18px;
rem

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			// height: 29px;
ゴミコード

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		z-index: 2;
z-indexはプロパティの末尾に

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  	// height: 1275.66px;
ゴミ残さない

2023-10-14 05:43 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			width: 343px;
絶対値

2023-10-18 13:35 UTC, twinbee-a-takahashi requested changes
ブラケット{}の内部に書かれるプロパティは必ずインデントを入れること。
コロンの後のスペース忘れがちなので、

<img width="399" alt="image" src="https://github.com/twinbee-official/it_freelance/assets/144518584/185ba05c-9afe-4af4-9fb7-1d3fb73cf183">
こういう検索を使ってみて、
:nth-とか以外のやつで引っかからないか、レビュー出す前に確認してもいいと思います。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> -	width: 100%;
positionの設定はまとめる。

```
.classname {
  position: absolute;
  left: 0;
  top: 50vh;
}
```

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> -
こういう // メニュー　とかの見出しの前は
改行１個入れておくと見やすいと思います。

基本２行以上の改行は入れないので、不要改行って書かれちゃってたと
思うんですが、見やすさを重視した改行ならアリです。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  					position: absolute;
イレギュラーなのですが、
positionは末尾にまとめて書いた方がいいです。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> -
ここは本来空いていてOKな改行です。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> -
コードの見やすさに関連しているので。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +	position: absolute;
position設定はまとめる。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  /* mainVisual st */
必ずしもクラス名を見出しに使わなければいけない訳ではないので、
日本語のがわかりやすくなるなら
`/* メインビジュアル st */`

とかにしちゃってもいいと思います。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  /* free_memberRegist_anchor st */
ここも　会員登録動線バナーでいいかも。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  /* sectionTitle st */
sectionTitle　にしてしまうと汎用性がないので、
いっそ　「見出し関連」にしちゃうとか。

他に見出しができた時にそこに追加していけばいいので。
見出し関連は共通して使えるので、ヘッダーの記述より上に置きましょう。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  .h2_sub {
sectionTitle　と言ってるのに.h2_subが出てきちゃってる。
だから見出し関連のがしっくり来るという訳です！

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +	padding-top:48px;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  	@include imgPath('canDo_twinbee_content_1','png');
アルファベットだとincludeはもう少し下にならない？

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  	&:nth-child(2) {
2から始まってると違和感。

.canDo_twinbee_contentに１の情報を入れずにこうしてみて。

```
.canDo_twinbee_content {
	align-items: center;
	background-color: $cl_fadePurple;
	background-repeat: no-repeat;
	background-size: contain;
	border-radius: 12px;
	display: flex;
	height: 483px;
	justify-content: flex-end;
	margin: 0px auto;
	margin-bottom: 40px;
	padding: 24px 30px;
	width: min(100%, 1072px);
        &:first-child {
          	@include imgPath('canDo_twinbee_content_1','png');
        }
        &:nth-child(2) {
          	@include imgPath('canDo_twinbee_content_2','png');
        }
        &:nth-child(3) {
          	@include imgPath('canDo_twinbee_content_3','png');
        }
        &:last-child {
          	@include imgPath('canDo_twinbee_content_4','png');
        }
}
```

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  		&_num {
font-weight: normal;を指定してほしいです。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  label {
HTMLタグのまま指定しない。必ずクラス名で。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  		border-left:none;
コロンの後のスペース

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  		background-color: #DAADFF;
共通して使われている色であれば変数使ってください。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	width: min(100%, 343px);
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		clear: both;
疑似要素のcontent は一番上に書いてあげた方がいいかも。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		width: min(100%, 343px);
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		display: block;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	display: block;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		border-bottom: none;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		font-size: 0.875rem;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  	background-color: #DAADFF;
色は変数使う

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	height: 52px;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  .job_introduct_tab label:has(:checked)::before {
こういう特殊な指定は見出しつけてあげた方がいい。

/* タブが選択された場合〜 */みたいな条件を明示する。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  .job_introduct_tab input {
input にクラス名で指定してほしい

.job_introduct_tabItem　とかなんでもいいので。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	padding-bottom: 40px;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	width: min(100%, 311px);
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	margin-top:64px;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +		display: block;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +		border-left: 8px solid transparent;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +		border-top: 15.94px solid #eacfff;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +		display: flex;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  		font-size: 32px;
rem

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +			font-size: 0.875rem;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +	padding: 40px 16px;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +	position: absolute;
positionの指定が重複しているので、
後に書かれているrelativeが当たっているが良い？

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	position: absolute;
どちらかにしてくださいー。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
>  	display: block;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +		height: 42px;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			font-size: 1rem;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +	background-color: #8DA5FA;
変数指定する

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +  border-radius: 4px;
この辺り、タブではなくスペースでインデントされてるのでタブで統一してください。

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +	font-size: 0.75rem;
インデント

2023-10-18 13:35 UTC, twinbee-a-kikuchi commented on src/_develop/_style/top.scss
> +		font-size: 1rem;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
>  	&_submitBtn input[type=submit] {
これやるなら、きちんとクラス名つける。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		font-size: 1.125rem;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	padding:64px 0px;
インデント、コロン後のスペース

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		height: 375px;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		background-color: none;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +			display: block;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +a.access_map_content_expandBtn {
aタグの指定を入れない。

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	left: calc(100% - 81.07%);
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	padding:64px 0px;
インデントとコロン後のスペース

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		font-size:1.25rem;
コロン後のスペース

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		width: min(100%, 343px);
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +	height: 134px;
インデント

2023-10-18 13:35 UTC, twinbee-a-takahashi commented on src/_develop/_style/top.scss
> +		height: 65px;
インデント

2023-10-25 23:47 UTC, closed without merging